name: Deploy Next.js Application

on:
  push:
    branches:
      - deploy-with-docker-ec2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      - name: Create .env file
        run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env && echo "SITE_URL=${{ secrets.SITE_URL }}" >> .env
      - name: Build Docker image
        run: docker build --tag ashleywpc/ci-project .
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish image to DOCKER Hub
        run: docker push ashleywpc/ci-project

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull ashleywpc/ci-project
      - name: Delete old container
        run: docker rm -f ci-project-container
      - name: Run Docker container
        run: docker run -d -p 3000:3000 --name ci-project-container ashleywpc/ci-project